<package format="3">
  <name>planner_map</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="xyt15080656916@qq.com">xyt</maintainer>
  <license>TODO: License declaration</license>

  <!-- 关键：使用 ament_cmake_auto 作为构建工具依赖 -->
  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <!-- 所有依赖 -->
  <depend>rclcpp</depend>
  <depend>visualization_msgs</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>nav_msgs</depend>
  <depend>pcl_conversions</depend>
  <depend>pcl_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2_geometry_msgs</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>